import {
  MessageSquare,
  UserCheck,
  GraduationCap,
  Wind,
  Smile,
  ShieldCheck,
  EyeOff,
  UserPlus,
  HelpCircle,
} from 'lucide-react';

export const NAV_SECTIONS = [
  {
    id: 'services',
    label: 'Layanan',
    width: 'w-[560px]',
    promoSpan: 'col-span-5',
    contentSpan: 'col-span-7',
    promo: {
      icon: MessageSquare,
      title: 'Temukan Solusi Tepat untuk Pikiranmu',
      desc: 'Dari mahasiswa hingga institusi kampus, Humind membantu menjaga kesehatan mental agar Anda tidak sendirian.',
      badge: 'Ruang Aman Konseling',
      gradient: 'from-sky-50 via-sky-50/70 to-blue-50/40 border-sky-100',
      iconBg: 'bg-humind-primary-500 text-white',
    },
    menuTitle: 'Pilihan Layanan',
    items: [
      {
        title: 'Humind for Individual',
        desc: 'Konseling 60 menit via Chat, Call, atau Video bersama psikolog berizin SIPP',
        to: '/psychologists',
        icon: UserCheck,
        iconStyle: 'bg-sky-50 text-humind-primary-600 border-sky-100 group-hover:bg-humind-primary-500 group-hover:text-white',
      },
      {
        title: 'Humind for Campus',
        desc: 'Program kemitraan kampus, BEM, & subsidi kuota konseling mahasiswa',
        badge: 'Soon',
        icon: GraduationCap,
        iconStyle: 'bg-emerald-50 text-emerald-600 border-emerald-100 group-hover:bg-emerald-600 group-hover:text-white',
      },
    ],
  },
  {
    id: 'selfcare',
    label: 'Self-Care',
    mobileLabel: 'Self-Care & Relaksasi',
    width: 'w-[560px]',
    promoSpan: 'col-span-5',
    contentSpan: 'col-span-7',
    promo: {
      icon: Wind,
      title: 'Pulihkan Energi Mentalmu Mandiri',
      desc: 'Langkah kecil setiap hari untuk menenangkan pikiran dan merawat kesehatan mental tanpa beban kognitif.',
      badge: '100% Gratis & Mandiri',
      gradient: 'from-teal-50 via-emerald-50/70 to-emerald-50/40 border-teal-100',
      iconBg: 'bg-teal-600 text-white',
    },
    menuTitle: 'Fitur Relaksasi Mandiri',
    items: [
      {
        title: 'Latihan Napas 60 Detik',
        desc: 'Panic button instan teknik Box Breathing (4-4-4) untuk redakan overthinking & panik',
        to: '/wellness/grounding',
        icon: Wind,
        iconStyle: 'bg-teal-50 text-teal-600 border-teal-100 group-hover:bg-teal-600 group-hover:text-white',
      },
      {
        title: 'Daily Mood Tracker',
        desc: 'Catat emosi harian, pemicu stres kuliah, dan pantau grafik suasana hati',
        to: '/wellness',
        icon: Smile,
        iconStyle: 'bg-amber-50 text-amber-600 border-amber-100 group-hover:bg-amber-500 group-hover:text-white',
      },
    ],
  },
  {
    id: 'about',
    label: 'Tentang Kami',
    width: 'w-[650px] max-w-[calc(100vw-2rem)]',
    align: 'center',
    promoSpan: 'col-span-4',
    contentSpan: 'col-span-8',
    columns: 2,
    promo: {
      icon: ShieldCheck,
      title: 'Tentang Kami',
      desc: 'Temukan berbagai informasi seputar Humind, transparansi etika, dan ruang aman pikiranmu di sini.',
      gradient: 'from-slate-50 via-sky-50/40 to-blue-50/20 border-slate-200/80',
      iconBg: 'bg-sky-100 text-humind-primary-600',
    },
    menuTitle: 'Tentang Kami',
    items: [
      {
        title: '100% Psikolog SIPP',
        desc: 'Seluruh mitra terverifikasi izin aktif HIMPSI',
        to: '/psychologists',
        icon: ShieldCheck,
        iconStyle: 'bg-blue-50 text-blue-600 border-blue-100 group-hover:bg-blue-600 group-hover:text-white',
      },
      {
        title: 'Mode Curhat Anonim',
        desc: 'Bebas pakai nama samaran tanpa stigma kampus',
        to: '/#ruang-aman',
        scrollTarget: 'ruang-aman',
        icon: EyeOff,
        iconStyle: 'bg-purple-50 text-purple-600 border-purple-100 group-hover:bg-purple-600 group-hover:text-white',
      },
      {
        title: 'Gabung Mitra',
        desc: 'Peluang kolaborasi praktik bagi psikolog SIPP',
        badge: 'Soon',
        icon: UserPlus,
        iconStyle: 'bg-amber-50 text-amber-600 border-amber-100 group-hover:bg-amber-600 group-hover:text-white',
      },
      {
        title: 'FAQ & Pusat Bantuan',
        desc: 'Temukan jawaban atas pertanyaan seputar sesi',
        to: '/#ruang-aman',
        scrollTarget: 'ruang-aman',
        icon: HelpCircle,
        iconStyle: 'bg-slate-100 text-slate-600 border-slate-200 group-hover:bg-slate-700 group-hover:text-white',
      },
    ],
  },
];
